<a href="https://colab.research.google.com/github/Pratikshya49/Concepts-and-Technologies-of-AI/blob/main/Workshop_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 4 (Task 1)
import numpy as np

# Task 1 – Working with different types of NumPy arrays
import numpy as np

print("Different Types of Arrays\n")

# 1.
arr_empty = np.empty((2, 2))
print("1. Empty 2x2 Array:")
print(arr_empty)

# 2.
arr_ones = np.ones((4, 2))
print("\n2. 4x2 Array of Ones:")
print(arr_ones)

# 3.
arr_fill_7 = np.full((3, 3), 7)
print("\n3. 3x3 Array Filled with 7:")
print(arr_fill_7)

# 4.
arr_zero_like = np.zeros_like(arr_fill_7)
print("\n4. Zero Array with Same Shape as Above:")
print(arr_zero_like)

# 5.
arr_one_like = np.ones_like(arr_fill_7)
print("\n5. Ones Array with Same Shape as Above:")
print(arr_one_like)

# 6.
my_numbers = [1, 2, 3, 4]
list_to_array = np.array(my_numbers)
print("\n6. Array Created from a List:")
print(list_to_array)

1. Empty Array 2x2:
 [[9.77765864e-316 0.00000000e+000]
 [6.87111027e-310 6.87111027e-310]]

2. Ones Array 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Filled Array 3x3 with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros Like Filled Array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

5. Ones Like Filled Array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

6. Numpy array from list:
 [1 2 3 4]


In [ ]:
# 4 (Task 2)

''' Manipulation in Array '''

# 1. Array with values 10 to 49
arr_10_49 = np.arange(10, 50)
print("\n1. Array 10 to 49:\n", arr_10_49)

# 2. 3x3 matrix with values 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 Matrix 0-8:\n", matrix_3x3)

# 3. 3x3 identity matrix
identity_3x3 = np.eye(3)
print("\n3. Identity Matrix 3x3:\n", identity_3x3)

# 4. Random array of size 30 and mean
rand_array = np.random.random(30)
print("\n4. Random Array of size 30:", rand_array)
print("Mean:", rand_array.mean())

# 5. 10x10 random array and min/max
rand_10x10 = np.random.random((10, 10))
print("\n5. 10x10 Random Array Min:", rand_10x10.min(), "Max:", rand_10x10.max())

# 6. Zero array of size 10, replace 5th element with 1
zero_arr = np.zeros(10)
zero_arr[4] = 1
print("\n6. Zero array with 5th element as 1:", zero_arr)

# 7. Reverse array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed Array:", reversed_arr)

# 8. 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. Border Array:\n", border_array)

# 9. 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard Pattern:\n", checkerboard)




1. Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix 0-8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Identity Matrix 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random Array of size 30: [0.1557717  0.01965161 0.3266818  0.67867428 0.81203068 0.99365933
 0.52196927 0.65202402 0.47398378 0.17128994 0.72652028 0.85189666
 0.57064214 0.82619584 0.65081351 0.12618778 0.57815419 0.41129683
 0.17158703 0.03855852 0.95097408 0.39276352 0.35127335 0.55035003
 0.64861947 0.69898365 0.55011581 0.50481862 0.78886624 0.8312227 ]
Mean: 0.534185888483655

5. 10x10 Random Array Min: 0.004408225411706379 Max: 0.9872509960330706

6. Zero array with 5th element as 1: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed Array: [0 4 0 0 2 1]

8. Border Array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. 8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]

In [ ]:
# 4 (Task 3)

''' Operations in Array '''

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add x + y
print("\n1. x + y:\n", x + y)

# 2. Subtract x - y
print("\n2. x - y:\n", x - y)

# 3. Multiply array with integer (example *3)
print("\n3. x * 3:\n", x * 3)

# 4. Square of each element
print("\n4. x squared:\n", x ** 2)

# 5. Dot products
print("\n5a. v.w =", np.dot(v, w))
print("5b. x.v =", np.dot(x, v))
print("5c. x.y =\n", np.dot(x, y))

# 6. Concatenate along rows and columns
print("\n6a. Concatenate x and y along rows:\n", np.concatenate((x, y), axis=0))
print("6b. Concatenate v and w along column:\n", np.column_stack((v, w)))


# 7. Concatenate x and v (will give error)
try:
    np.concatenate((x, v), axis=0)
except ValueError as e:
    print("\n7. Concatenating x and v Error:", e)
    print("Reason: x is 2D and v is 1D, shapes not compatible for concatenation along axis 0")



1. x + y:
 [[ 6  8]
 [10 13]]

2. x - y:
 [[-4 -4]
 [-4 -3]]

3. x * 3:
 [[ 3  6]
 [ 9 15]]

4. x squared:
 [[ 1  4]
 [ 9 25]]

5a. v.w = 219
5b. x.v = [29 77]
5c. x.y =
 [[19 22]
 [50 58]]

6a. Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b. Concatenate v and w along column:
 [[ 9 11]
 [10 12]]

7. Concatenating x and v Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: x is 2D and v is 1D, shapes not compatible for concatenation along axis 0


In [ ]:
# 4 (Task 4)

''' Matrix Operation using Array '''

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A^-1 = I
A_inv = np.linalg.inv(A)
print("\n1. A * A_inv =\n", np.dot(A, A_inv))

# 2. Prove AB != BA
print("\n2. AB =\n", np.dot(A, B))
print("   BA =\n", np.dot(B, A))
print("AB != BA:", not np.allclose(np.dot(A, B), np.dot(B, A)))

# 3. Prove (AB)^T = B^T A^T
AB_T = np.dot(A, B).T
B_T_A_T = np.dot(B.T, A.T)
print("\n3. (AB)^T =\n", AB_T)
print("   B^T A^T =\n", B_T_A_T)
print("Equality:", np.allclose(AB_T, B_T_A_T))

# Solve linear equations using matrix inverse
# Equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

coeff_matrix = np.array([[2, -3, 1],
                         [1, -1, 2],
                         [3, 1, -1]])
constants = np.array([-1, -3, 9])

# Solve using np.linalg.inv
solution = np.dot(np.linalg.inv(coeff_matrix), constants)
print("\nSolution using inverse:\n", solution)



1. A * A_inv =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. AB =
 [[23 13]
 [51 29]]
   BA =
 [[36 44]
 [13 16]]
AB != BA: True

3. (AB)^T =
 [[23 51]
 [13 29]]
   B^T A^T =
 [[23 51]
 [13 29]]
Equality: True

Solution using inverse:
 [ 2.  1. -2.]
